### ISSUE TITLE
Guide for setting up cors-anywhere & websocket proxies in nodejs?

### ISSUE THREAD

**Issue by dirkdickbutt** [zoomerdev/dlive-superchats#4]
Is there a guide anywhere on how to set all of these up? I tried setting up cors-anywhere in nodejs but have been having a time with it.

**Comment by zoomerdev** [comment]
Hi, I can post a more in depth guide later, but I recommend cloudflare workers cors-anywhere. And I wrote a custom websocket proxy server I can open source. Are you trying to deploy this yourself or just contribute?

**Comment by dirkdickbutt** [comment]
deploy myself so I can try to help some other dlive streamers set this up themselves.

**Comment by zoomerdev** [comment]
sure, other streamers can use the instance I host if you're interested, it's in the readme.

I've published the source for the websocket and http proxies here https://github.com/zoomerdev/websocket-header-proxy

**Comment by dirkdickbutt** [comment]
didn't want to make a new issue for this, and I might just be retarded, but after I run yarn build, it seems to exit rather than running a web-server. Is there something I'm missing?
```
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 760 bytes {0} [built]
        + 3 hidden modules
Done in 7.56s.
```

**Comment by zoomerdev** [comment]
Yarn start for development
Yarn build for production build

**Comment by dirkdickbutt** [comment]
Oh I see. It was confusing me because it was still building with all of the demo stuff even though I ran yarn build. I'm guessing that I configured something improperly?

**Comment by zoomerdev** [comment]
if you go to `https://localhost:4141` it will always render the demo. You need to go to `https://localhost:4141/#yourdlivename` to connect to a dlive page

**Comment by dirkdickbutt** [comment]
Holy crap I feel stupid. Thanks for that. It worked immediately.
